package com.thopham.projects.desktop.demo.domain.api

//import org.junit.Assert.assertTrue
//import org.junit.Before
//import org.junit.Test
//import org.junit.runner.RunWith
//import org.springframework.beans.factory.annotation.Autowired
//import org.springframework.boot.test.context.SpringBootTest
//import org.springframework.test.context.junit4.SpringJUnit4ClassRunner

//@SpringBootTest
//@RunWith(SpringJUnit4ClassRunner::class)
class CategoryClientTest{
//    companion object{
//        const val PRINT_FORM_REGULAR_DATA = "eyJhY2NvdW50Ijp7Im5hbWUiOiJNaW5oIMSQ4bupYyJ9LCJyZXN0YXVyYW50X2luZm8iOnsibmFtZSI6Ik5ow6AgaMOgbmcgTWluaCDEkOG7qWMiLCJwaG9uZSI6IjA5MDQ4MzcwOTUiLCJhZGRyZXNzIjoiMzQyIEtoxrDGoW5nIMSQw6xuaCwgVGhhbmggWHXDom4sIEjDoCBO4buZaSIsInR5cGVfcHJpbnQiOlsiMSIsIjIiLCIzIiwiNCIsIjUiLCI2IiwiNyIsIjgiLCI5IiwiMTAiLCIxMSIsIjEyIl0sImxvZ28iOiJodHRwczpcL1wvdG0ud2VzYXZlLnZuXC9jZG5cL3Jlc3RhdXJhbnRcLzI2NDdcL3dlYlwvMjAxOFwvMTBcLzA0XC8xNTM4NjIwNzE3XzYwMzcucG5nIiwidGFsayI6IlhpbiBj4bqjbSDGoW4gcXXDvSBraMOhY2ghIDxcL2JyPlxyXG5IZWxsbyBIaSJ9LCJwcmludF90ZW0iOmZhbHNlLCJwb3N0Ijp7InJlc19pZCI6MjY0NywiaWRfcHJvbW90aW9uIjpudWxsLCJjdXNfbmFtZSI6IiIsInRlbGVwaG9uZSI6IiIsIm1ldGhvZCI6IiIsInR5cGVvcmRlciI6IjIiLCJvcmRlcl90eXBlIjoicG9zIiwiZGVsaXZlcnlfdHlwZSI6ImludGFibGUiLCJkZXRhaWwiOlt7ImlkIjoxMzM5MiwicXVhbnRpdHkiOjQsInByaWNlIjoyMDAwMCwidHlwZSI6MiwicHJpbmNpcGxlIjowLCJub3RlIjpudWxsLCJzaXplIjpudWxsLCJ0b3BpbmciOm51bGwsInNpemVfa2V5IjpudWxsLCJpZF9vcHQiOjEzMzkyLCJzcGVjaWFsX25vdGUiOm51bGwsImRpc2NvdW50IjpudWxsLCJ0aW1lIjoxNTU2OTM1Mjc2LCJuYW1lIjoiYWFhYSIsInRvdGFsIjoiODAsMDAwIn1dLCJjdXNfaWQiOi0xLCJwYWdlX2lkIjowLCJjdXNfbWFpbCI6IiIsInRvdGFsX3ByaWNlX3BheSI6IjgwMDAwIiwiZGlzY291bnQiOiIiLCJzdXBwbGVtZW50YXJ5IjoiIiwidmF0IjoiIiwidG90YWxfcHJpY2VfZW5kIjoiODAwMDAiLCJpbnB1dF9tb25leSI6IjgwMDAwIiwibW9uZXlfY2hhbmdlIjoiIiwibm90ZSI6IiIsImRlbGl2ZXIiOjAsInBvc2l0aW9uIjoiQsOgbiBjYzYiLCJpZF9iaWxsIjo4MDk1MywidGFibGVfZmxvb3IiOiJCw6BuIGNjNiAtIFThuqduZyAxIn0sImZ1bGwiOjF9"
//        const val PRINT_FORM_TEA_DATA = "W3sicmVzdGF1cmFudCI6IlBo4bufIEfDoCBUYSBQaOG7kSBD4buVIiwibG9nbyI6Imh0dHBzOi8vdG0ud2VzYXZlLnZuL2Nkbi9yZXN0YXVyYW50LzE2MjUvd2ViLzIwMTgvMDEvMTgvMTUxNjI2ODI5OV8yLnBob2dhM18ucG5nIiwicGhvbmUiOiIwOTg2MTQ3OTQ5IiwidGFibGUiOiJU4bqnbmcgMSAtIELDoG4gVmlwMyIsImNvdW50IjoiMS8xIiwiaWQiOjEyNjAxLCJzaXplIjoicyIsIm5hbWUiOiJHw6AgaOG6pXAgcsaw4bujdSIsInByaWNlIjo0NTUwMDAsInF1YW50aXR5IjoxLCJ0b3BpbmciOlt7ImlkIjo1MTIyLCJuYW1lIjoiS2hvYWkgdMOieTEyMyIsInByaWNlIjoiNTAwMCIsInF1YW50aXR5IjoxfV0sInNwZWNpYWxfbm90ZSI6W119XQ=="
//    }
//    @Autowired
//    lateinit var categoryClient: CategoryClient
//    @Before
//    fun init(){
//
//    }
//    //@Test
//    fun testFetchPrintForm(){
//        val content = categoryClient.fetchPrintForm(1, 0, PRINT_FORM_REGULAR_DATA)
//        assertTrue(content, false)
//    }
}